package cli

import (
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/RomanAgaltsev/quiver/internal/gen"
)

func newGenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gen",
		Short: "Generate a collection from an API description",
		Long: "Turn a machine-readable API description into a runnable quiver collection.\n\n" +
			"Only OpenAPI 3.x is supported today; proto and GraphQL generation are planned.",
	}
	cmd.AddCommand(newGenOpenAPICmd())
	return cmd
}

func newGenOpenAPICmd() *cobra.Command {
	var (
		outDir string
		force  bool
		check  bool
	)

	cmd := &cobra.Command{
		Use:   "openapi <spec>",
		Short: "Generate a collection from an OpenAPI 3.x document",
		Long: "Generate one request file per operation, plus a collection.yaml carrying the " +
			"spec's servers and security schemes.\n\n" +
			"Re-generation is safe: .qv/gen.lock records what was written, and a file you " +
			"have edited since is skipped and reported rather than overwritten. Commit the " +
			"lockfile — unlike .qv/history/, it is part of the collection.\n\n" +
			"Path parameters become {{var}} templates; supply them with -V name=value or an " +
			"environment file.\n\n" +
			"Exit codes: 0 generated (skips included), 1 only for --check drift, " +
			"2 the spec is unreadable, is Swagger 2.0, or the output cannot be written.",
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runGenOpenAPI(cmd.OutOrStdout(), args[0], outDir, force, check)
		},
	}

	f := cmd.Flags()
	// Named "output" rather than "out" on purpose: the root command already owns
	// the -o shorthand for the output *format*, and pflag panics when a locally
	// declared shorthand collides with an inherited flag of a different name.
	// Declaring the same name shadows it cleanly for this command instead.
	f.StringVarP(&outDir, "output", "o", ".", "output directory for the generated collection")
	f.BoolVar(&force, "force", false, "overwrite files you have edited since they were generated")
	f.BoolVar(&check, "check", false, "report what would change and exit 1 if anything would; write nothing")

	return cmd
}

func runGenOpenAPI(w io.Writer, specPath, outDir string, force, check bool) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return configErr(fmt.Errorf("read spec: %w", err))
	}
	doc, err := gen.LoadDocument(data)
	if err != nil {
		return configErr(err)
	}

	coll, files, notes := gen.Generate(doc)

	lock, err := gen.LoadLock(outDir)
	if err != nil {
		return configErr(err)
	}

	lock.SetSource(specPath, data)
	lock.Generator = "qv " + version()

	if check {
		rep, pErr := gen.Plan(outDir, files, coll, lock, force)
		if pErr != nil {
			return configErr(pErr)
		}
		if pErr := printReport(w, rep, notes, true); pErr != nil {
			return pErr
		}
		if rep.Changed() {
			return runErr(errors.New(
				"the collection is out of date with the spec; re-run without --check"))
		}
		return nil
	}

	rep, err := gen.Write(outDir, files, coll, lock, force)
	if err != nil {
		return configErr(err)
	}
	return printReport(w, rep, notes, false)
}

// printReport is the generation report. It is documentation as much as output:
// it is the only place a user finds out that a file was skipped, that an
// endpoint left the spec, or that a security scheme could not be expressed.
func printReport(w io.Writer, rep *gen.Report, notes []string, dryRun bool) error {
	// One error, carried to the end: a report that stops halfway through because
	// a pipe closed would hide the skips, which are the part that matters.
	var perr error
	say := func(format string, args ...any) {
		if perr != nil {
			return
		}
		_, perr = fmt.Fprintf(w, format, args...)
	}

	verb := "generated"
	if dryRun {
		verb = "would generate"
	}

	parts := []string{fmt.Sprintf("%s %d file(s)", verb, len(rep.Written))}
	if n := len(rep.Restored); n > 0 {
		parts = append(parts, fmt.Sprintf("restored %d", n))
	}
	if n := len(rep.SkippedEdited); n > 0 {
		parts = append(parts, fmt.Sprintf("skipped %d (hand-edited)", n))
	}
	if n := len(rep.SkippedUnmanaged); n > 0 {
		parts = append(parts, fmt.Sprintf("skipped %d (not generated by qv)", n))
	}
	if n := len(rep.Orphaned); n > 0 {
		parts = append(parts, fmt.Sprintf("%d orphaned", n))
	}
	say("%s\n", strings.Join(parts, ", "))

	list(say, "skipped", rep.SkippedEdited, "edited since generation; --force overwrites")
	list(say, "unmanaged", rep.SkippedUnmanaged, "not written by qv gen; left alone")
	list(say, "restored", rep.Restored, "")
	list(say, "orphaned", rep.Orphaned, "no longer in the spec; left on disk")

	if len(notes) > 0 {
		say("\nnotes:\n")
		for _, n := range sorted(notes) {
			say("  - %s\n", n)
		}
	}
	return perr
}

func list(say func(string, ...any), label string, paths []string, why string) {
	if len(paths) == 0 {
		return
	}
	suffix := ""
	if why != "" {
		suffix = " (" + why + ")"
	}
	say("  %s:%s\n", label, suffix)
	for _, p := range sorted(paths) {
		say("    %s\n", p)
	}
}

// sorted copies before sorting: the report must not reorder the caller's slice,
// which is the same one the lockfile and the tests read.
func sorted(ss []string) []string {
	out := append([]string(nil), ss...)
	sort.Strings(out)
	return out
}
