package cli

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/RomanAgaltsev/quiver/internal/gen"
	"github.com/RomanAgaltsev/quiver/internal/transport/grpcx"
)

func newGenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gen",
		Short: "Generate a collection from an API description",
		Long: "Turn a machine-readable API description into a runnable quiver collection.\n\n" +
			"Only OpenAPI 3.x is supported today; proto and GraphQL generation are planned.",
	}
	cmd.AddCommand(newGenOpenAPICmd(), newGenProtoCmd())
	return cmd
}

func newGenOpenAPICmd() *cobra.Command {
	var (
		outDir string
		force  bool
		check  bool
	)

	cmd := &cobra.Command{
		Use:   "openapi <spec>",
		Short: "Generate a collection from an OpenAPI 3.x document",
		Long: "Generate one request file per operation, plus a collection.yaml carrying the " +
			"spec's servers and security schemes.\n\n" +
			"Re-generation is safe: .qv/gen.lock records what was written, and a file you " +
			"have edited since is skipped and reported rather than overwritten. Commit the " +
			"lockfile — unlike .qv/history/, it is part of the collection.\n\n" +
			"Path parameters become {{var}} templates; supply them with -V name=value or an " +
			"environment file.\n\n" +
			"Exit codes: 0 generated (skips included), 1 only for --check drift, " +
			"2 the spec is unreadable, is Swagger 2.0, or the output cannot be written.",
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runGenOpenAPI(cmd.OutOrStdout(), args[0], outDir, force, check)
		},
	}

	f := cmd.Flags()
	// Named "output" rather than "out" on purpose: the root command already owns
	// the -o shorthand for the output *format*, and pflag panics when a locally
	// declared shorthand collides with an inherited flag of a different name.
	// Declaring the same name shadows it cleanly for this command instead.
	f.StringVarP(&outDir, "output", "o", ".", "output directory for the generated collection")
	f.BoolVar(&force, "force", false, "overwrite files you have edited since they were generated")
	f.BoolVar(&check, "check", false, "report what would change and exit 1 if anything would; write nothing")

	return cmd
}

func runGenOpenAPI(w io.Writer, specPath, outDir string, force, check bool) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return configErr(fmt.Errorf("read spec: %w", err))
	}
	doc, err := gen.LoadDocument(data)
	if err != nil {
		return configErr(err)
	}

	coll, files, notes := gen.Generate(doc)

	lock, err := gen.LoadLock(outDir)
	if err != nil {
		return configErr(err)
	}

	lock.SetSource(specPath, data)
	lock.Generator = "qv " + version()

	if check {
		rep, pErr := gen.Plan(outDir, files, coll, lock, force)
		if pErr != nil {
			return configErr(pErr)
		}
		if pErr := printReport(w, rep, notes, true); pErr != nil {
			return pErr
		}
		if rep.Changed() {
			return runErr(errors.New(
				"the collection is out of date with the spec; re-run without --check"))
		}
		return nil
	}

	rep, err := gen.Write(outDir, files, coll, lock, force)
	if err != nil {
		return configErr(err)
	}
	return printReport(w, rep, notes, false)
}

// printReport is the generation report. It is documentation as much as output:
// it is the only place a user finds out that a file was skipped, that an
// endpoint left the spec, or that a security scheme could not be expressed.
func printReport(w io.Writer, rep *gen.Report, notes []string, dryRun bool) error {
	// One error, carried to the end: a report that stops halfway through because
	// a pipe closed would hide the skips, which are the part that matters.
	var perr error
	say := func(format string, args ...any) {
		if perr != nil {
			return
		}
		_, perr = fmt.Fprintf(w, format, args...)
	}

	verb := "generated"
	if dryRun {
		verb = "would generate"
	}

	parts := []string{fmt.Sprintf("%s %d file(s)", verb, len(rep.Written))}
	if n := len(rep.Restored); n > 0 {
		parts = append(parts, fmt.Sprintf("restored %d", n))
	}
	if n := len(rep.SkippedEdited); n > 0 {
		parts = append(parts, fmt.Sprintf("skipped %d (hand-edited)", n))
	}
	if n := len(rep.SkippedUnmanaged); n > 0 {
		parts = append(parts, fmt.Sprintf("skipped %d (not generated by qv)", n))
	}
	if n := len(rep.Orphaned); n > 0 {
		parts = append(parts, fmt.Sprintf("%d orphaned", n))
	}
	say("%s\n", strings.Join(parts, ", "))

	list(say, "skipped", rep.SkippedEdited, "edited since generation; --force overwrites")
	list(say, "unmanaged", rep.SkippedUnmanaged, "not written by qv gen; left alone")
	list(say, "restored", rep.Restored, "")
	list(say, "orphaned", rep.Orphaned, "no longer in the spec; left on disk")

	if len(notes) > 0 {
		say("\nnotes:\n")
		for _, n := range sorted(notes) {
			say("  - %s\n", n)
		}
	}
	return perr
}

func list(say func(string, ...any), label string, paths []string, why string) {
	if len(paths) == 0 {
		return
	}
	suffix := ""
	if why != "" {
		suffix = " (" + why + ")"
	}
	say("  %s:%s\n", label, suffix)
	for _, p := range sorted(paths) {
		say("    %s\n", p)
	}
}

// sorted copies before sorting: the report must not reorder the caller's slice,
// which is the same one the lockfile and the tests read.
func sorted(ss []string) []string {
	out := append([]string(nil), ss...)
	sort.Strings(out)
	return out
}

func newGenProtoCmd() *cobra.Command {
	var (
		outDir    string
		reflect   string
		target    string
		plaintext bool
		depth     int
		force     bool
		check     bool
	)

	cmd := &cobra.Command{
		Use:   "proto [files...]",
		Short: "Generate a gRPC collection from .proto files or a reflective server",
		Long: "Generate one request file per unary RPC, plus a collection.yaml carrying the " +
			"target as {{grpc_target}}.\n\n" +
			"Descriptors come from .proto files (with --target naming the server to call) or " +
			"from a live server's reflection service (--reflect). Streaming RPCs are skipped " +
			"and reported: quiver is unary-only.\n\n" +
			"Messages are generated as protojson, so field names are lowerCamelCase and will " +
			"not match the .proto verbatim — a proto pet_id is sent as petId.\n\n" +
			"Re-generation follows the same lockfile rules as `qv gen openapi`.\n\n" +
			"Exit codes: 0 generated (skips included), 1 only for --check drift, " +
			"2 bad flags, an uncompilable .proto, an unreachable server, or unwritable output.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runGenProto(cmd.Context(), cmd.OutOrStdout(), genProtoArgs{
				files: args, reflect: reflect, target: target, plaintext: plaintext,
				depth: depth, outDir: outDir, force: force, check: check,
			})
		},
	}

	f := cmd.Flags()
	f.StringVarP(&outDir, "output", "o", ".", "output directory for the generated collection")
	f.StringVar(&reflect, "reflect", "", "enumerate from this server's reflection service (host:port)")
	f.StringVar(&target, "target", "", "server the generated requests call (required with .proto files)")
	f.BoolVar(&plaintext, "plaintext", false, "generated requests dial without TLS")
	f.IntVar(&depth, "depth", gen.DefaultProtoDepth, "how deep to nest generated message skeletons")
	f.BoolVar(&force, "force", false, "overwrite files you have edited since they were generated")
	f.BoolVar(&check, "check", false, "report what would change and exit 1 if anything would; write nothing")

	return cmd
}

type genProtoArgs struct {
	files     []string
	reflect   string
	target    string
	plaintext bool
	depth     int
	outDir    string
	force     bool
	check     bool
}

// validate rejects an incoherent invocation before anything is compiled or
// dialled, which is the package's standing rule: a run that will be refused must
// not touch a real system first.
func (a genProtoArgs) validate() error {
	switch {
	case len(a.files) == 0 && a.reflect == "":
		return errors.New("name one or more .proto files, or pass --reflect host:port")
	case len(a.files) > 0 && a.reflect != "":
		return errors.New("--reflect and .proto file arguments are two sources for one run; pick one")
	case len(a.files) > 0 && a.target == "":
		return errors.New(
			"--target host:port is required with .proto files: a .proto says what to call, not where")
	case a.depth <= 0:
		return fmt.Errorf("--depth must be positive, got %d", a.depth)
	}
	return nil
}

func runGenProto(ctx context.Context, w io.Writer, a genProtoArgs) error {
	if err := a.validate(); err != nil {
		return configErr(err)
	}

	lock, err := gen.LoadLock(a.outDir)
	if err != nil {
		return configErr(err)
	}

	infos, opts, err := protoSource(ctx, a, lock)
	if err != nil {
		return configErr(err)
	}
	lock.Generator = "qv " + version()

	files, notes, err := gen.MapProto(infos, opts)
	if err != nil {
		return configErr(err)
	}

	target := a.target
	if target == "" {
		target = a.reflect
	}
	coll := gen.ProtoCollection(target)

	if a.check {
		rep, pErr := gen.Plan(a.outDir, files, coll, lock, a.force)
		if pErr != nil {
			return configErr(pErr)
		}
		if pErr := printReport(w, rep, notes, true); pErr != nil {
			return pErr
		}
		if rep.Changed() {
			return runErr(errors.New(
				"the collection is out of date with its descriptors; re-run without --check"))
		}
		return nil
	}

	rep, err := gen.Write(a.outDir, files, coll, lock, a.force)
	if err != nil {
		return configErr(err)
	}
	return printReport(w, rep, notes, false)
}

// protoSource enumerates from whichever descriptor source was chosen and records
// it in the lock.
func protoSource(ctx context.Context, a genProtoArgs, lock *gen.Lock) ([]grpcx.MethodInfo, gen.ProtoOptions, error) {
	opts := gen.ProtoOptions{Plaintext: a.plaintext, Depth: a.depth, OutDir: a.outDir}

	if a.reflect != "" {
		infos, err := grpcx.EnumerateFromReflection(ctx, a.reflect, a.plaintext)
		if err != nil {
			return nil, opts, err
		}
		lock.SetReflectSource(a.reflect)
		return infos, opts, nil
	}

	infos, err := grpcx.EnumerateFromProtoFiles(a.files)
	if err != nil {
		return nil, opts, err
	}
	// Absolute here so MapProto can make them relative to each generated file;
	// grpc.proto_files resolves against the request file, not the caller's cwd.
	abs := make([]string, 0, len(a.files))
	for _, p := range a.files {
		ap, aErr := filepath.Abs(p)
		if aErr != nil {
			return nil, opts, fmt.Errorf("resolve %s: %w", p, aErr)
		}
		abs = append(abs, ap)
	}
	opts.ProtoFiles = abs

	// The lock's source is the .proto set, hashed so a changed descriptor is
	// visible the way a changed OpenAPI document is.
	lock.SetSource(strings.Join(a.files, ","), protoBytes(a.files))
	return infos, opts, nil
}

// protoBytes concatenates the .proto sources so the lock can fingerprint the
// whole set rather than only the first file.
func protoBytes(paths []string) []byte {
	var all []byte
	for _, p := range paths {
		b, err := os.ReadFile(p)
		if err != nil {
			// Unreadable is already impossible here — enumeration compiled them
			// — but a partial hash is better than a panic and still changes when
			// the readable files do.
			continue
		}
		all = append(all, b...)
	}
	return all
}
